packages:
  - apps/*
  - packages/*
  - apis/*
catalog:
  '@eslint/js': ^9.36.0
  '@hono/node-server': ^1.19.5
  '@orpc/server': ^1.7.5
  '@orpc/zod': ^1.7.5
  '@tailwindcss/vite': ^4.0.6
  '@tanstack/react-router': ^1.132.0
  '@types/node': ^22.10.2
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  better-sqlite3: ^12.4.1
  '@types/better-sqlite3': ^7.6.9
  bun-types: ^1.2.23
  eslint: ^9.36.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  globals: ^16.4.0
  hono: ^4.6.9
  kysely: ^0.27.3
  prettier: ^3.5.3
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwindcss: ^4.0.6
  tsx: ^4.19.2
  typescript: ^5.7.2
  typescript-eslint: ^8.45.0
  vitest: ^3.0.5
  zod: ^4.0.10
