import { createHash } from "node:crypto";
import { access, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { getZodClientTemplateContext, maybePretty } from "openapi-zod-client";
import type {
	OpenAPIObject,
	OperationObject,
	ParameterObject,
	PathItemObject,
	ReferenceObject,
	RequestBodyObject,
} from "openapi3-ts";
import { parse as parseYaml } from "yaml";

import { loadTimebackEnv } from "../src/env";

type Service = "qti" | "oneroster" | "caliper" | "powerpath" | "edubridge";

type ServiceGenerationConfig = {
	specEnvironment: "staging" | "production";
};

type GenerationResult = {
	service: Service;
	status: "generated" | "skipped" | "failed";
	message?: string;
};

type OperationMetadata = {
	pathTemplate: string;
	parameters: Map<string, ParameterRequirement>;
	body?: OperationBodyMetadata;
};

type ParameterRequirement = {
	required: boolean;
};

type OperationBodyMetadata = {
	required: boolean;
	contentTypes: ReadonlyArray<string>;
	description?: string;
};

type TemplateContext = ReturnType<typeof getZodClientTemplateContext>;

type ServiceTypePrefix = {
	caliper: "Caliper";
	edubridge: "Edubridge";
	oneroster: "OneRoster";
	powerpath: "Powerpath";
	qti: "Qti";
};

const SPEC_DIR = fileURLToPath(new URL("../openapi", import.meta.url));
const SRC_DIR = fileURLToPath(new URL("../src", import.meta.url));
const FILE_HEADER =
	"// This file is auto-generated by scripts/generate.ts. Do not edit manually.\n";

const SERVICE_CONFIG: Record<Service, ServiceGenerationConfig> = {
	qti: { specEnvironment: "staging" },
	oneroster: { specEnvironment: "staging" },
	caliper: { specEnvironment: "staging" },
	powerpath: { specEnvironment: "staging" },
	edubridge: { specEnvironment: "staging" },
};

const SERVICE_TYPE_PREFIX: ServiceTypePrefix = {
	caliper: "Caliper",
	edubridge: "Edubridge",
	oneroster: "OneRoster",
	powerpath: "Powerpath",
	qti: "Qti",
};

const OPERATION_ALLOWLIST: Partial<Record<Service, ReadonlySet<string>>> = {
	oneroster: new Set([
		"getAllClasses",
		"getClass",
		"getAllCourses",
		"getCourse",
		"getAllStudents",
		"getStudentsForClass",
		"getStudent",
		"getAllUsers",
		"getUser",
		"getUserWithDemographics",
		"getAgents",
		"getAgentFor",
		"getOrg",
		"getAllAssessmentLineItems",
		"getAllAssessmentResults",
	]),
	powerpath: new Set([
		"getCourseProgress",
		"getAllPlacementTests",
		"getCurrentLevel",
		"getNextPlacementTest",
		"getSubjectProgress",
	]),
	// Generate full spec when allowlist entry is undefined.
	caliper: new Set(),
	qti: new Set(),
	edubridge: new Set([
		"listFactsDateRange",
		"listFactsWeekly",
		"getHighestGradeMastered",
		"getStudentTimeSaved",
		"getMapProfile",
	]),
};

const HTTP_METHODS = [
	"get",
	"put",
	"post",
	"delete",
	"options",
	"head",
	"patch",
	"trace",
] as const;

async function main() {
	loadTimebackEnv();

	const results: GenerationResult[] = [];

	for (const service of Object.keys(SERVICE_CONFIG) as Service[]) {
		const result = await generateForService(service, SERVICE_CONFIG[service]);
		results.push(result);
	}

	for (const result of results) {
		const base = `[${result.service}]`;
		const message = result.message ? ` ${result.message}` : "";
		process.stdout.write(`${base} ${result.status}${message}\n`);
	}

	const failures = results.filter((result) => result.status === "failed");
	if (failures.length > 0) {
		process.exitCode = 1;
	}
}

async function generateForService(
	service: Service,
	config: ServiceGenerationConfig,
): Promise<GenerationResult> {
	const specPath = join(SPEC_DIR, service, `${config.specEnvironment}.yaml`);

	if (!(await fileExists(specPath))) {
		return {
			service,
			status: "failed",
			message: `Spec not found for ${config.specEnvironment} (${specPath})`,
		};
	}

	const outputDir = join(SRC_DIR, service, "generated");
	await mkdir(outputDir, { recursive: true });

	try {
		const specRaw = await readFile(specPath, "utf8");
		const openApiDoc = parseYaml(specRaw) as OpenAPIObject;

		const context = getZodClientTemplateContext(openApiDoc, {
			groupStrategy: "none",
			withAlias: true,
			shouldExportAllSchemas: true,
			shouldExportAllTypes: true,
			withAllResponses: true,
			withDefaultValues: true,
		});

		const metadataByAlias = buildOperationMetadata(openApiDoc);

		const schemaNameRegistry = new Set(Object.keys(context.schemas));
		const servicePrefix = SERVICE_TYPE_PREFIX[service];

		await removeLegacyFile(join(outputDir, "operations.ts"));

		const additionalSchemas = new Map<string, string>();
		const usedSchemaNames = new Set<string>();

		const { source: operationSpecsSource } = buildOperationSpecsFile(
			context,
			metadataByAlias,
			schemaNameRegistry,
			service,
			servicePrefix,
			usedSchemaNames,
			additionalSchemas,
		);

		resolveSchemaDependencies(
			usedSchemaNames,
			context.schemas,
			schemaNameRegistry,
		);

		const schemasSource = buildSchemasFile(
			context,
			additionalSchemas,
			usedSchemaNames,
		);

		await writeGeneratedFile(
			join(outputDir, "schemas.ts"),
			sanitizeSchemaCode(schemasSource),
		);

		await writeGeneratedFile(
			join(outputDir, "operation-specs.ts"),
			sanitizeSchemaCode(operationSpecsSource),
		);

		await writeGeneratedFile(
			join(outputDir, "index.ts"),
			buildIndexFile(servicePrefix),
		);

		await writeMetadataFile(outputDir, service, specPath);

		return {
			service,
			status: "generated",
		};
	} catch (error) {
		return {
			service,
			status: "failed",
			message: error instanceof Error ? error.message : "Unknown error",
		};
	}
}

function buildSchemasFile(
	context: TemplateContext,
	additionalSchemas: Map<string, string>,
	usedSchemaNames: Set<string>,
): string {
	const lines: string[] = [];

	const additionalEntries = Array.from(additionalSchemas.entries()).sort(
		(a, b) => a[0].localeCompare(b[0]),
	);

	const baseEntries: Array<readonly [string, string]> = [];
	for (const [name, schema] of Object.entries(context.schemas)) {
		if (usedSchemaNames.has(name)) {
			baseEntries.push([name, schema]);
		}
	}

	const schemaEntries = [...baseEntries, ...additionalEntries];

	if (schemaEntries.length === 0) {
		return "export {};";
	}

	lines.push('import { z } from "zod";');
	lines.push("");

	for (const [name, schema] of schemaEntries) {
		lines.push(`export const ${name} = ${schema};`);
	}

	if (schemaEntries.length > 0) {
		lines.push("");
	}

	const emittedNames = new Set(schemaEntries.map(([name]) => name));

	for (const [name] of schemaEntries) {
		const shouldEmitType =
			context.emittedType?.[name] ?? emittedNames.has(name);
		if (shouldEmitType) {
			lines.push(`export type ${name} = z.infer<typeof ${name}>;`);
		}
	}

	return lines.join("\n");
}

function buildOperationSpecsFile(
	context: TemplateContext,
	metadataByAlias: Map<string, OperationMetadata>,
	schemaRegistry: Set<string>,
	service: Service,
	servicePrefix: string,
	usedSchemaNames: Set<string>,
	additionalSchemas: Map<string, string>,
): { source: string; operationSchemaNames: Set<string> } {
	const lines: string[] = [];
	const operationSchemaNames = new Set<string>();

	lines.push(
		"function defineOperationSpecs<const T extends OperationSpecMap>(specs: T): T {",
	);
	lines.push("  return specs;");
	lines.push("}");
	lines.push("");

	const operationBlocks: string[] = [];

	for (const endpoint of context.endpoints) {
		const alias = endpoint.alias;
		if (!alias) {
			continue;
		}
		const metadata = metadataByAlias.get(alias);
		if (!metadata) {
			continue;
		}

		const allowlist = OPERATION_ALLOWLIST[service];
		if (allowlist && !allowlist.has(alias)) {
			continue;
		}

		const blockLines: string[] = [];
		blockLines.push(`  ${alias}: {`);
		blockLines.push(`    alias: "${alias}",`);
		blockLines.push(`    method: "${endpoint.method}",`);
		blockLines.push(`    path: "${endpoint.path}",`);
		blockLines.push(
			`    pathTemplate: ${JSON.stringify(metadata.pathTemplate)},`,
		);

		if (endpoint.description) {
			blockLines.push(
				`    description: ${JSON.stringify(endpoint.description)},`,
			);
		}

		if (endpoint.requestFormat) {
			blockLines.push(`    requestFormat: "${endpoint.requestFormat}",`);
		}

		const parameterLines = buildParameterLines(
			endpoint.parameters ?? [],
			metadata,
			schemaRegistry,
			usedSchemaNames,
		);
		blockLines.push("    parameters: [");
		if (parameterLines.length > 0) {
			for (const parameterLine of parameterLines) {
				blockLines.push(parameterLine);
			}
		}
		blockLines.push("    ] as const,");

		if (metadata.body) {
			const bodyDefinition = buildBodyDefinition(
				alias,
				endpoint.parameters ?? [],
				metadata.body,
				schemaRegistry,
				servicePrefix,
				usedSchemaNames,
				operationSchemaNames,
				additionalSchemas,
			);
			if (bodyDefinition) {
				blockLines.push(`    body: ${bodyDefinition},`);
			}
		}

		const responseExpression = rewriteSchemaExpression(
			endpoint.response,
			schemaRegistry,
		);
		collectSchemaReferences(
			responseExpression,
			usedSchemaNames,
			schemaRegistry,
			responseExpression.startsWith("z.") ? undefined : operationSchemaNames,
		);
		const namedResponse = ensureNamedSchema(
			responseExpression,
			alias,
			"Response",
			additionalSchemas,
			schemaRegistry,
			servicePrefix,
			usedSchemaNames,
			operationSchemaNames,
		);
		blockLines.push(`    response: ${namedResponse},`);

		const errorLines = buildErrorLines(
			endpoint.errors ?? [],
			schemaRegistry,
			usedSchemaNames,
			operationSchemaNames,
		);
		blockLines.push("    errors: [");
		if (errorLines.length > 0) {
			for (const errorLine of errorLines) {
				blockLines.push(errorLine);
			}
		}
		blockLines.push("    ] as const,");
		blockLines.push("  },");
		operationBlocks.push(blockLines.join("\n"));
	}

	const chunkSize = 1;
	const chunkCount = Math.ceil(operationBlocks.length / chunkSize);

	for (let index = 0; index < chunkCount; index += 1) {
		const start = index * chunkSize;
		const end = start + chunkSize;
		lines.push(`const operationSpecMapChunk${index} = {`);
		for (const block of operationBlocks.slice(start, end)) {
			lines.push(block);
		}
		lines.push("} as const satisfies OperationSpecMap;");
		lines.push("");
	}

	if (chunkCount === 0) {
		lines.push(
			"const operationSpecMap = {} as const satisfies OperationSpecMap;",
		);
	} else {
		const intersection = Array.from(
			{ length: chunkCount },
			(_value, index) => `typeof operationSpecMapChunk${index}`,
		).join(" & ");

		lines.push(`const operationSpecMap: ${intersection} = {`);
		for (let index = 0; index < chunkCount; index += 1) {
			lines.push(`  ...operationSpecMapChunk${index},`);
		}
		lines.push("} as const satisfies OperationSpecMap;");
	}
	lines.push("");
	lines.push(
		"export const operationSpecs: typeof operationSpecMap = defineOperationSpecs(operationSpecMap);",
	);
	lines.push("");
	lines.push(
		`export type ${servicePrefix}OperationSpecs = typeof operationSpecs;`,
	);
	lines.push(
		`export type ${servicePrefix}OperationAlias = keyof ${servicePrefix}OperationSpecs;`,
	);

	const schemaImports = Array.from(operationSchemaNames).sort();
	const usesZod = lines.some((line) => line.includes("z."));
	const headerLines: string[] = [];
	if (usesZod) {
		headerLines.push('import { z } from "zod";');
	}
	headerLines.push('import type { OperationSpecMap } from "../../types";');
	if (schemaImports.length > 0) {
		headerLines.push(
			`import { ${schemaImports.join(", ")} } from "./schemas";`,
		);
	}
	headerLines.push("");

	const source = [...headerLines, ...lines].join("\n");
	return { source, operationSchemaNames };
}

function buildIndexFile(servicePrefix: string): string {
	return [
		`export type { ${servicePrefix}OperationAlias, ${servicePrefix}OperationSpecs } from "./operation-specs";`,
		`export { operationSpecs } from "./operation-specs";`,
		'export * from "./schemas";',
	].join("\n");
}

function toPascalCase(value: string): string {
	return value
		.split(/[^a-zA-Z0-9]+/)
		.filter((segment) => segment.length > 0)
		.map((segment) => segment[0].toUpperCase() + segment.slice(1))
		.join("");
}

function ensureNamedSchema(
	expression: string,
	alias: string,
	suffix: string,
	additionalSchemas: Map<string, string>,
	schemaRegistry: Set<string>,
	servicePrefix: string,
	usedSchemaNames: Set<string>,
	operationSchemaNames?: Set<string>,
): string {
	if (!expression.startsWith("z.")) {
		collectSchemaReferences(
			expression,
			usedSchemaNames,
			schemaRegistry,
			operationSchemaNames,
		);
		return expression;
	}

	collectSchemaReferences(expression, usedSchemaNames, schemaRegistry);

	const baseName = `${servicePrefix}${toPascalCase(alias)}${suffix}`;
	let candidate = baseName;
	let counter = 1;
	while (schemaRegistry.has(candidate) || additionalSchemas.has(candidate)) {
		candidate = `${baseName}${counter}`;
		counter += 1;
	}

	const normalizedExpression = expression.replace(/\bschemas\./g, "");
	additionalSchemas.set(candidate, normalizedExpression);
	usedSchemaNames.add(candidate);
	schemaRegistry.add(candidate);
	if (operationSchemaNames) {
		operationSchemaNames.add(candidate);
	}
	return candidate;
}

function collectSchemaReferences(
	expression: string,
	usedSchemaNames: Set<string>,
	schemaRegistry: Set<string>,
	operationSchemaNames?: Set<string>,
): void {
	for (const name of schemaRegistry) {
		if (usedSchemaNames.has(name)) {
			continue;
		}
		const regex = new RegExp(`\\b${name}\\b`);
		if (regex.test(expression)) {
			usedSchemaNames.add(name);
			if (operationSchemaNames) {
				operationSchemaNames.add(name);
			}
		}
	}
}

function resolveSchemaDependencies(
	usedSchemaNames: Set<string>,
	schemaDefinitions: Record<string, string>,
	schemaRegistry: Set<string>,
): void {
	const queue = Array.from(usedSchemaNames);
	const visited = new Set<string>();

	while (queue.length > 0) {
		const name = queue.pop();
		if (!name || visited.has(name)) {
			continue;
		}
		visited.add(name);

		const definition = schemaDefinitions[name];
		if (!definition) {
			continue;
		}

		for (const candidate of schemaRegistry) {
			if (usedSchemaNames.has(candidate)) {
				continue;
			}
			const regex = new RegExp(`\\b${candidate}\\b`);
			if (regex.test(definition)) {
				usedSchemaNames.add(candidate);
				queue.push(candidate);
			}
		}
	}
}

function buildParameterLines(
	parameters: Array<{
		name: string;
		type?: string;
		description?: string;
		schema: string;
	}>,
	metadata: OperationMetadata,
	schemaRegistry: Set<string>,
	usedSchemaNames: Set<string>,
): string[] {
	const lines: string[] = [];

	for (const parameter of parameters) {
		const location = normalizeParameterLocation(parameter.type);
		if (!location || location === "body") {
			continue;
		}

		const lookupName =
			location === "path"
				? sanitizeParameterName(parameter.name, location)
				: parameter.name;
		const requirement = metadata.parameters.get(
			createParameterKey(location, lookupName),
		);
		const required = requirement?.required ?? false;

		const fieldLines: string[] = [];
		fieldLines.push("{");
		fieldLines.push(`  name: ${JSON.stringify(parameter.name)},`);
		fieldLines.push(`  location: "${location}",`);
		fieldLines.push(`  required: ${required ? "true" : "false"},`);
		if (parameter.description) {
			fieldLines.push(
				`  description: ${JSON.stringify(parameter.description)},`,
			);
		}
		const schemaExpression = rewriteSchemaExpression(
			parameter.schema,
			schemaRegistry,
		);
		collectSchemaReferences(schemaExpression, usedSchemaNames, schemaRegistry);
		fieldLines.push(`  schema: ${schemaExpression},`);
		fieldLines.push("},");

		const block = fieldLines.map((line) => `      ${line}`).join("\n");
		lines.push(block);
	}

	return lines;
}

function buildBodyDefinition(
	alias: string,
	parameters: Array<{
		name: string;
		type?: string;
		description?: string;
		schema: string;
	}>,
	bodyMetadata: OperationBodyMetadata,
	schemaRegistry: Set<string>,
	servicePrefix: string,
	usedSchemaNames: Set<string>,
	operationSchemaNames: Set<string>,
	additionalSchemas: Map<string, string>,
): string | undefined {
	const bodyParameter = parameters.find(
		(parameter) => normalizeParameterLocation(parameter.type) === "body",
	);

	if (!bodyParameter) {
		return undefined;
	}

	const segments: string[] = [];
	segments.push("{");
	segments.push(`  required: ${bodyMetadata.required ? "true" : "false"},`);
	if (bodyParameter.description ?? bodyMetadata.description) {
		const description =
			bodyParameter.description ?? bodyMetadata.description ?? "";
		segments.push(`  description: ${JSON.stringify(description)},`);
	}
	const schemaExpression = rewriteSchemaExpression(
		bodyParameter.schema,
		schemaRegistry,
	);
	collectSchemaReferences(
		schemaExpression,
		usedSchemaNames,
		schemaRegistry,
		operationSchemaNames,
	);
	const namedSchema = ensureNamedSchema(
		schemaExpression,
		alias,
		"RequestBody",
		additionalSchemas,
		schemaRegistry,
		servicePrefix,
		usedSchemaNames,
		operationSchemaNames,
	);
	segments.push(`  schema: ${namedSchema},`);
	segments.push(
		`  contentTypes: ${JSON.stringify([...bodyMetadata.contentTypes])} as const,`,
	);
	segments.push("}");

	const block = segments
		.map((line, index) => {
			if (index === 0) {
				return line;
			}
			if (index === segments.length - 1) {
				return `    ${line}`;
			}
			return `      ${line}`;
		})
		.join("\n");

	return block;
}

function buildErrorLines(
	errors: Array<{
		status: number | "default";
		description?: string;
		schema: string;
	}>,
	schemaRegistry: Set<string>,
	usedSchemaNames: Set<string>,
	operationSchemaNames: Set<string>,
): string[] {
	const lines: string[] = [];

	for (const error of errors) {
		const errorLines: string[] = [];
		errorLines.push("{");
		if (typeof error.status === "number") {
			errorLines.push(`  status: ${error.status},`);
		} else {
			errorLines.push('  status: "default",');
		}
		if (error.description) {
			errorLines.push(`  description: ${JSON.stringify(error.description)},`);
		}
		const schemaExpression = rewriteSchemaExpression(
			error.schema,
			schemaRegistry,
		);
		collectSchemaReferences(
			schemaExpression,
			usedSchemaNames,
			schemaRegistry,
			schemaExpression.startsWith("z.") ? undefined : operationSchemaNames,
		);
		errorLines.push(`  schema: ${schemaExpression},`);
		errorLines.push("},");

		const block = errorLines.map((line) => `      ${line}`).join("\n");
		lines.push(block);
	}

	return lines;
}

function buildOperationMetadata(
	openApiDoc: OpenAPIObject,
): Map<string, OperationMetadata> {
	const entries = new Map<string, OperationMetadata>();

	for (const [pathTemplate, pathItemValue] of Object.entries(
		openApiDoc.paths ?? {},
	)) {
		const pathItem = pathItemValue as PathItemObject;
		const baseParameters = pathItem.parameters ?? [];

		for (const method of HTTP_METHODS) {
			const operation = pathItem[method];
			if (!operation) {
				continue;
			}

			if (operation.deprecated) {
				continue;
			}

			const alias = computeAlias(method, pathTemplate, operation);
			const parameterMap = collectParameters(
				baseParameters,
				operation.parameters ?? [],
				openApiDoc,
			);
			const parameterRequirements = new Map<string, ParameterRequirement>();

			for (const parameter of parameterMap.values()) {
				if (!parameter.in) {
					continue;
				}
				const location = normalizeParameterLocation(parameter.in);
				if (!location || location === "body") {
					continue;
				}
				const sanitizedName = sanitizeParameterName(parameter.name, location);
				parameterRequirements.set(createParameterKey(location, sanitizedName), {
					required:
						location === "path" ? true : Boolean(parameter.required ?? false),
				});
			}

			const requestBody = resolveRequestBody(operation.requestBody, openApiDoc);
			const bodyMetadata = requestBody
				? {
						required: Boolean(requestBody.required ?? false),
						contentTypes: Array.from(
							new Set(Object.keys(requestBody.content ?? {})),
						),
						description: requestBody.description,
					}
				: undefined;

			entries.set(alias, {
				pathTemplate,
				parameters: parameterRequirements,
				body: bodyMetadata,
			});
		}
	}

	return entries;
}

function collectParameters(
	pathParameters: ReadonlyArray<ParameterObject | ReferenceObject>,
	operationParameters: ReadonlyArray<ParameterObject | ReferenceObject>,
	doc: OpenAPIObject,
): Map<string, ParameterObject> {
	const map = new Map<string, ParameterObject>();

	for (const parameter of pathParameters) {
		const resolved = resolveParameter(parameter, doc);
		const key = `${resolved.in ?? ""}:${resolved.name}`;
		map.set(key, resolved);
	}

	for (const parameter of operationParameters) {
		const resolved = resolveParameter(parameter, doc);
		const key = `${resolved.in ?? ""}:${resolved.name}`;
		map.set(key, resolved);
	}

	return map;
}

function resolveParameter(
	parameter: ParameterObject | ReferenceObject,
	doc: OpenAPIObject,
): ParameterObject {
	if (isReferenceObject(parameter)) {
		return resolveRef(parameter.$ref, doc) as ParameterObject;
	}
	return parameter;
}

function resolveRequestBody(
	requestBody: OperationObject["requestBody"],
	doc: OpenAPIObject,
): RequestBodyObject | undefined {
	if (!requestBody) {
		return undefined;
	}
	if (isReferenceObject(requestBody)) {
		return resolveRef(requestBody.$ref, doc) as RequestBodyObject;
	}
	return requestBody as RequestBodyObject;
}

function resolveRef(ref: string, doc: OpenAPIObject): unknown {
	if (!ref.startsWith("#/")) {
		throw new Error(`Unsupported ref: ${ref}`);
	}
	const pathSegments = ref
		.slice(2)
		.split("/")
		.map((segment) => segment.replace(/~1/g, "/").replace(/~0/g, "~"));

	let current: unknown = doc;
	for (const segment of pathSegments) {
		if (typeof current !== "object" || current === null) {
			return undefined;
		}
		current = (current as Record<string, unknown>)[segment];
	}
	return current;
}

function computeAlias(
	method: string,
	pathTemplate: string,
	operation: OperationObject,
): string {
	if (operation.operationId) {
		return operation.operationId;
	}
	const sanitizedPath = pathTemplate
		.replace(/[{}]/g, "")
		.split(/\W+/)
		.filter((segment) => segment.length > 0)
		.map((segment) => segment[0]?.toUpperCase() + segment.slice(1))
		.join("");
	return `${method}${sanitizedPath}`;
}

function normalizeParameterLocation(
	type?: string,
): "path" | "query" | "header" | "body" | undefined {
	if (!type) {
		return undefined;
	}
	const value = type.toLowerCase();
	if (
		value === "path" ||
		value === "query" ||
		value === "header" ||
		value === "body"
	) {
		return value;
	}
	if (value === "headers") {
		return "header";
	}
	return undefined;
}

function sanitizeParameterName(name: string, location: string): string {
	if (location !== "path") {
		return name;
	}
	const segments = name.split(/[-_]/).filter((segment) => segment.length > 0);
	if (segments.length === 0) {
		return name;
	}
	return segments
		.map((segment, index) =>
			index === 0 ? segment : segment[0]?.toUpperCase() + segment.slice(1),
		)
		.join("");
}

function createParameterKey(location: string, name: string): string {
	return `${location}:${name}`;
}

function rewriteSchemaExpression(
	schema: string,
	schemaNames: ReadonlySet<string>,
): string {
	if (schemaNames.size === 0) {
		return schema;
	}

	const reserved = new Set(["z"]);
	let result = "";
	let token = "";
	let inString: false | "'" | '"' | "`" = false;
	let escaping = false;

	const flushToken = () => {
		if (!token) {
			return;
		}
		if (schemaNames.has(token) && !reserved.has(token)) {
			result += token;
		} else {
			result += token;
		}
		token = "";
	};

	for (const char of schema) {
		if (inString) {
			result += char;
			if (escaping) {
				escaping = false;
				continue;
			}
			if (char === "\\") {
				escaping = true;
				continue;
			}
			if (char === inString) {
				inString = false;
			}
			continue;
		}

		if (char === "'" || char === '"' || char === "`") {
			flushToken();
			inString = char;
			result += char;
			continue;
		}

		if (/[_a-zA-Z0-9]/.test(char)) {
			token += char;
			continue;
		}

		flushToken();
		result += char;
	}

	flushToken();
	return result;
}

function sanitizeSchemaCode(code: string): string {
	const withoutNullEnums = code.replace(
		/z\.enum\(\[(.*?)\]\)/gs,
		(match: string, inner: string) => {
			if (!/\bnull\b/.test(inner)) {
				return match;
			}
			const values = inner
				.split(",")
				.map((part: string) => part.trim())
				.filter((part: string) => part.length > 0 && part !== "null");
			return `z.enum([${values.join(", ")}])`;
		},
	);

	const withLazyAnnotations = withoutNullEnums.replace(
		/const ([A-Z][A-Za-z0-9_]*) = z\.lazy/g,
		"const $1: z.ZodLazy<z.ZodTypeAny> = z.lazy",
	);

	return withLazyAnnotations.replace(
		/z\.discriminatedUnion\(\s*"[^"]+",\s*\[/g,
		"z.union([",
	);
}

async function writeGeneratedFile(
	path: string,
	contents: string,
): Promise<void> {
	const formatted = maybePretty(`${FILE_HEADER}\n${contents}`, {
		filepath: path,
	});
	const normalized = formatted.endsWith("\n") ? formatted : `${formatted}\n`;
	await writeFile(path, normalized, "utf8");
}

async function writeMetadataFile(
	outputDir: string,
	service: Service,
	specPath: string,
): Promise<void> {
	const specHash = await computeFileHash(specPath);
	const metadata = {
		service,
		specPath,
		specHash,
		generatedAt: new Date().toISOString(),
	};
	const metadataPath = join(outputDir, "metadata.json");
	const serialized = `${JSON.stringify(metadata, null, 2)}\n`;
	await writeFile(metadataPath, serialized, "utf8");
}

async function computeFileHash(path: string): Promise<string> {
	const buffer = await readFile(path);
	const hash = createHash("sha256");
	hash.update(buffer);
	return hash.digest("hex");
}

async function removeLegacyFile(path: string): Promise<void> {
	if (await fileExists(path)) {
		await rm(path);
	}
}

async function fileExists(path: string): Promise<boolean> {
	try {
		await access(path);
		return true;
	} catch {
		return false;
	}
}

function isReferenceObject(value: unknown): value is ReferenceObject {
	return typeof value === "object" && value !== null && "$ref" in value;
}

await main();
